/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.heisenbug;

import com.codeborne.selenide.Configuration;
import com.codeborne.selenide.Selenide;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.ValueSource;

import static com.codeborne.selenide.CollectionCondition.size;
import static com.codeborne.selenide.Selenide.$;
import static com.codeborne.selenide.Selenide.$$;
import static com.codeborne.selenide.Selenide.closeWebDriver;
import static com.codeborne.selenide.Selenide.localStorage;
import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.refresh;
import static com.codeborne.selenide.Selenide.sleep;

class TodoMvcTest {
  @ParameterizedTest
  @ValueSource(strings = {"встать", "проснуться", "кофе", "чай"})
  void hardFlow(String todoItem) {
    $$(".todo-list .view").shouldHave(size(0));
    $(".new-todo").val(todoItem).pressEnter();
    $$(".todo-list .view").shouldHave(size(1));
  }

  @BeforeEach
  void setUp() {
    open("https://todomvc.com/examples/react/");
    localStorage().clear();
    refresh();
  }
}
